export default {
    REGISTER_LOADING: "REGISTER_LOADING",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",

    LOGIN_LOADING: "LOGIN_LOADING",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",

    LOGOUT_LOADING: "LOGOUT_LOADING",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",
    
    CLEAR_AUTH_STATE: "CLEAR_AUTH_STATE",
    
    GET_CONTACTS_LOADING:"GET_CONTACTS_LOADING",
    GET_CONTACTS_SUCCESS:"GET_CONTACTS_SUCCESS",
    GET_CONTACTS_FAIL:"GET_CONTACTS_FAIL",
}
