export default {
    REGISTER_LOADING: "REGISTER_LOADING",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",

    LOGIN_LOADING: "LOGIN_LOADING",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    
    CLEAR_AUTH_STATE:"CLEAR_AUTH_STATE"
}
